name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Define Variables
      run: |
        export REPO_NAME="$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"
        echo "::set-env name=RepositoryName::$REPO_NAME"
        echo "::set-env name=RepositoryNameLowcase::$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')"
        export GITHUB_ACTOR_LOWERCASE="$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')"
        echo "::set-env name=GitHubActorLowercase::$GITHUB_ACTOR_LOWERCASE"      

    - name: Build and Pack with dotnet
      run: dotnet pack --configuration Release -o .\${{ env.RepositoryName }}\publish 
      
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
      
    - name: Add Source
      run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/KloderGit/index.json" -UserName KloderGit -Password ${{ secrets.GITHUB_TOKEN }}
      
    - name: Push
      run: dotnet nuget push -s GitHub -k ${{ secrets.GITHUB_TOKEN }} .\${{ env.RepositoryName }}\publish\*.nupkg   
